export enum BOOKS {
  RSND1 = "RSND1",
  RSND2 = "RSND2",
  SUTRA = "SUTRA",
  GLOSSARIO = "GLOSSARIO",
}

export enum FIELDS {
  CONTENT = "CONTENT",
  CENNI_STORICI = "CENNI_STORICI",
  NOTE = "NOTE",
}
